server:
  servlet:
    context-path: /
  port: 5433

spring:
  freemarker:
    check-template-location: false
  profiles:
    active: dev
  application:
    name: user-consumer-service
  mvc:
    throw-exception-if-no-handler-found: true   #出现错误时, 直接抛出异常
  resources:
    add-mappings: false   #关闭工程中的资源文件建立映射